### ISSUE TITLE
User defined search order list

### ISSUE THREAD

**Issue by sdasda7777** [GreenDiscord/vlc-rpc#12]
Hi, I noticed two problems that could be solved relatively simply with one feature:
- For some reason one of albums I'd like to listen to returns no results on Apple Music, and conversely another one returns no results on Spotify. That indicates to me there should be a way to search not only one, but both. However, I think it might be useful to also have the option to search on other sites, for example Google, in case neither of the two can find anything (if that's possible, I think it should be, but to be honest it doesn't matter that much at this stage).
- Secondly, it seems the query for Apple Music only searches for music, but I think it might be desirable to search first for music and then in general if no results are found. However that might not be desirable for all users, so I propose the order and the exact wording of the queries be user selectable in config.js, something along these lines:

```js
rpc: {
    // Change where to fetch the album artwork
    whereToFetchOnline:
    [
        {handler: "apple", query: "https://itunes.apple.com/search?media=music&term=%TITLE%+%ARTIST%"},
        {handler: "spotify", query: /*the equivalent of the query above for spotify*/},
        {handler: "apple", query: "https://itunes.apple.com/search?term=%TITLE%+%ARTIST%"},
        {handler: "google", query: "https://images.google.com/q=%TITLE%+%ARTIST%"},
    ]
},
```

**Comment by GreenDiscord** [comment]
Hey this one, still figuring the api out for the massive album art site.

**Comment by GreenDiscord** [comment]
Hey this one, still figuring the api out for the massive album art site.

**Comment by sdasda7777** [comment]
This issue doesn't seem relevant anymore, so I'll close it. Feel free to look into that API, though, that would still be cool 😄
