### ISSUE TITLE
Playing music with UPNP sources causes vlc to not use meta data and only file name

### ISSUE THREAD

**Issue by MattTheTekie** [GreenDiscord/vlc-rpc#16]
Playing music with UPNP sources causes vlc to not use meta data and only file name. I had to apply this PR to get here tho instead of it not showing its playing anything. https://github.com/GreenDiscord/vlc-rpc/pull/13
![image](https://github.com/GreenDiscord/vlc-rpc/assets/94870997/04a1f324-0bfc-4f0f-8711-0d12bdc303cb)

**Comment by MattTheTekie** [comment]
It would also be nice if we had the option to cache the image from http://localhost:8080/art

**Comment by sdasda7777** [comment]
> It would also be nice if we had the option to cache the image from http://localhost:8080/art

That can't be done, as far as I know, not practically anyways. You need to be able to distribute the image to other Discord users, which would mean either hosting them in some form, which is illegal in most cases. However I think it theoretically could be possible to do something like an override, so that a specific image URL would be used in some instances.

**Comment by MattTheTekie** [comment]
> > It would also be nice if we had the option to cache the image from http://localhost:8080/art
> 
> That can't be done, as far as I know, not practically anyways. You need to be able to distribute the image to other Discord users, which would mean either hosting them in some form, which is illegal in most cases. However I think it theoretically could be possible to do something like an override, so that a specific image URL would be used in some instances.

Can you add ` something like an override, so that a specific image URL would be used in some instances.`?

**Comment by sdasda7777** [comment]
> Playing music with UPNP sources causes vlc to not use meta data and only file name

Could you provide some example so that I could try it out, by the way? I actually have no clue what that is 😅

**Comment by MattTheTekie** [comment]
> > Playing music with UPNP sources causes vlc to not use meta data and only file name
> 
> Could you provide some example so that I could try it out, by the way? I actually have no clue what that is 😅

I can screen record.

**Comment by GreenDiscord** [comment]
> > It would also be nice if we had the option to cache the image from http://localhost:8080/art
> 
> 
> 
> That can't be done, as far as I know, not practically anyways. You need to be able to distribute the image to other Discord users, which would mean either hosting them in some form, which is illegal in most cases. However I think it theoretically could be possible to do something like an override, so that a specific image URL would be used in some instances.

Bit confused on the last bit, in theory you could obviously use metadata to get it, but it wouldn't work very well due to multiple types of album art, only idea I have is what was said about uploading the album art to a server, but that is very illegal.

**Comment by sdasda7777** [comment]
> > > Playing music with UPNP sources causes vlc to not use meta data and only file name
> > 
> > 
> > Could you provide some example so that I could try it out, by the way? I actually have no clue what that is 😅
> 
> I can screen record.

Either that, or some explanation on how to replicate your setup would be fine.

**Comment by MattTheTekie** [comment]
> 
Can we get VLC to show the name of the song using metadata in UPNP instead of the filename?
Can you add something like an override, so that a specific image URL would be used in some instances?

**Comment by GreenDiscord** [comment]
> > > Playing music with UPNP sources causes vlc to not use meta data and only file name
> 
> > 
> 
> > Could you provide some example so that I could try it out, by the way? I actually have no clue what that is 😅
> 
> 
> 
> I can screen record.

Also this issue I already know off, i implanted a fix a while ago now which didn't fetch the meta data due to it being slightly different in some case. Also, its a fix for a wide amount of sources (capture cars streaming, cameras, live streams, etc). I will have a look at vlc.js and try to implement a fix

**Comment by GreenDiscord** [comment]
> > 
> 
> Can we get VLC to show the name of the song using metadata in UPNP instead of the filename?
> 
> Can you add something like an override, so that a specific image URL would be used in some instances?

Well should be able to, if the album art is already hosted publicly (like spotify n apple), maybe if the song had metadata for a filename url? Where are you listenting to the music from tho, because upnp is local host.

**Comment by MattTheTekie** [comment]
https://files.catbox.moe/qvn8lr.mkv

**Comment by MattTheTekie** [comment]
> 

Thank you. I sent a video.

**Comment by MattTheTekie** [comment]
> > > 
> > 
> > 
> > Can we get VLC to show the name of the song using metadata in UPNP instead of the filename?
> > Can you add something like an override, so that a specific image URL would be used in some instances?
> 
> Well should be able to, if the album art is already hosted publicly (like spotify n apple), maybe if the song had metadata for a filename url? Where are you listenting to the music from tho, because upnp is local host.

Second question isnt related to the first. I just want the option to set a url in the config file for what image should go to the RPC if you get the idea 😉

**Comment by GreenDiscord** [comment]
Could you send one of the files as example?

**Comment by MattTheTekie** [comment]
> Could you send one of the files as example?

What do you mean. I sent a video. It's on my UPNP server on my phone.

**Comment by MattTheTekie** [comment]
If you put any MP3 file into a UPNP server and play it through VLC you're gonna get the same result. You just have to use [sdasda7777](https://github.com/sdasda7777) fork to get the result instead of nothing with this version on this repo here.

**Comment by MattTheTekie** [comment]
> > > > Playing music with UPNP sources causes vlc to not use meta data and only file name
> > 
> > 
> > > 
> > 
> > 
> > > Could you provide some example so that I could try it out, by the way? I actually have no clue what that is 😅
> > 
> > 
> > I can screen record.
> 
> Also this issue I already know off, i implanted a fix a while ago now which didn't fetch the meta data due to it being slightly different in some case. Also, its a fix for a wide amount of sources (capture cars streaming, cameras, live streams, etc). I will have a look at vlc.js and try to implement a fix

Please do so when you get the chance.

**Comment by sdasda7777** [comment]
> If you put any MP3 file into a UPNP server and play it through VLC you're gonna get the same result. You just have to use [sdasda7777](https://github.com/sdasda7777) fork to get the result instead of nothing with this version on this repo here.

I actually don't really know why that could be, the fork should be pretty much the same, afaik 😅

**Comment by MattTheTekie** [comment]
> > If you put any MP3 file into a UPNP server and play it through VLC you're gonna get the same result. You just have to use [sdasda7777](https://github.com/sdasda7777) fork to get the result instead of nothing with this version on this repo here.
> 
> I actually don't really know why that could be, the fork should be pretty much the same, afaik 😅

For me the fork shows the MP3 like this, but the application shows this. Without the fork it doesn't reconize anything playing over UPNP.
![image](https://github.com/GreenDiscord/vlc-rpc/assets/94870997/d413e80a-4cde-448d-8d67-6b9dff1456aa)

`http://192.168.92.60:57645/b64/H4sIAAAAAAAAANMvLskvSkxP1U_NLc1JLElN0TfQ9y0tzkzWdyxNyUzN005LTSzR0w4qTarUDijKL8hILdHW1Q7JSC1O1XYsSgWxtF0SK4u1NYISUzLztV1TMks09XILjAFhh6KlWQAAAA==.mp3`

**Comment by MattTheTekie** [comment]
![image](https://github.com/GreenDiscord/vlc-rpc/assets/94870997/da3185c5-adbf-4e2e-8df3-981b641c41ee)

**Comment by MattTheTekie** [comment]
Found a workaround that needs to be implemented. the
song name needs to be extracted from `"name":"Bastille+-+Pompeii+(Audien+Remix).mp3",` on the same part with
`"current":"current"`` from
http://localhost:8080/requests/playlist.json
oh yeah, http://localhost:8080/requests/status.json doesn't show it right btw.

Example;
`{
                      "ro":"ro",
                      "type":"leaf",
                      "name":"Bastille+-+Pompeii+(Audien+Remix).mp3",
                      "id":"13411",
                      "duration":352,
                      "uri":"http://192.168.92.60:57645/b64/H4sIAAAAAAAAANMvLskvSkxP1U_NLc1JLElN0TfQ9y0tzkzWd0osLsnMyUnV1tUOyM8tSM3M1NZwLE3JTM3TDkrNzazQ1MstMAYAuxjD-T8AAAA=.mp3",
                      "current":"current"
                    },`

**Comment by MattTheTekie** [comment]
@sdasda7777 @GreenDiscord

**Comment by MattTheTekie** [comment]
I'm going to pause this, as I think this is a due to the server encoding the file names like this.

**Comment by MattTheTekie** [comment]
We can close this issue. It was my UPNP server settings. I got it working now.
