### ISSUE TITLE
Option for custom URL for image in RPC.

### ISSUE THREAD

**Issue by MattTheTekie** [GreenDiscord/vlc-rpc#17]
Can you add option in the config file for a custom image URL?

**Comment by sdasda7777** [comment]
I think I have a pretty good idea how to do that, I'll look into it unless @GreenDiscord would like to do it himself.

**Comment by GreenDiscord** [comment]
Could you please giveme the problem your having with album art, What has made you like custom urls?

**Comment by MattTheTekie** [comment]
> 

It's not a issues it's a feature request

**Comment by GreenDiscord** [comment]
Oh, Ok.

**Comment by GreenDiscord** [comment]
Pinned as a reminder

**Comment by sdasda7777** [comment]
I think I found an example where this feature would be help: Metal Gear Rising OST. Not sure what the exact reason is, but neither library is able to find the cover. Possibly the fact both Spotify and Apple Music list the album artist as "Various Artists" doesn't help, the fact only vocalist is listed as the song artist there might be a second issue.

![image](https://github.com/GreenDiscord/vlc-rpc/assets/17746796/5813cde8-e15f-4d5a-aaaf-2b4a5636a25d)

![image](https://github.com/GreenDiscord/vlc-rpc/assets/17746796/ff598d90-0ebb-422c-a1e8-37ea007b360d)

**Comment by GreenDiscord** [comment]
Ok that makes sense.. I'm just thinking about any issues this may cause. It should work though.

**Comment by sdasda7777** [comment]
I'll look into this once the Youtube thing gets sorted out. Also funnily enough, this is once instance where it really goes over the 128 character Discord state limit 😂

**Comment by sdasda7777** [comment]
Slight issue arises, where the user should choose the `"musichoarders"` provider to for the best experience, but also something like `"static-overrides"` to use overrides.

I think there should be a more robust solution to this, but it does appear that JS objects are required to follow order of insertion when iterating, meaning `Object.keys({a: "c", b:"d"})` evaluates to `['a', 'b']` and `Object.keys({b:"d", a: "c"})` evaluates to `['b', 'a']`. That could be leveraged to define fetching order as `{"static-overrides": ..., "musichoarders": ..., others}`. Of course, there currently isn't a way to give user more control over this, other than the initial provider that will be tried.

**Comment by MattTheTekie** [comment]
I'm glad to see this thread continuing. 😊
