### ISSUE TITLE
crashing when playing songs with metadata

### ISSUE THREAD

**Issue by gwylius** [GreenDiscord/vlc-rpc#2]
works perfectly, until i play a song that has metadata in it. more specifically the "title" section of the metadata filled out.

**Comment by GreenDiscord** [comment]
Already fixed :)

**Comment by GreenDiscord** [comment]
Just a thought, what is the error?

**Comment by GreenDiscord** [comment]
[Fixed](https://github.com/GreenDiscord/vlc-rpc/releases/tag/V1.1.8) with latest release
