### ISSUE TITLE
Move default config out of the `config/` folder, add versioning and stuff

### ISSUE THREAD

**Issue by sdasda7777** [GreenDiscord/vlc-rpc#25]
Default config should not be in the `config/` folder, because it shouldn't be modified by the user.

Also add a version to it, so it's easy to keep track of.

**Comment by GreenDiscord** [comment]
Could you expand on that, I think tho a UI would be nice.

**Comment by sdasda7777** [comment]
Basically I meant pretty much just #27. Wdym by UI? 😅
