### ISSUE TITLE
Unhandled error: No results found for some albums when using 'spotify' as source

### ISSUE THREAD

**Issue by sdasda7777** [GreenDiscord/vlc-rpc#5]
Hey, the whole thing does seem to work in general, which I'm really impressed by, but when I tried to switch to 'spotify' as image source, I'm suddenly getting this error on some albums, even for fairly common ones which I know for a fact are on Spotify.

Doesn't happen for all, though: For example '...And Out Come The Wolves' by Rancid and 'Damaged' by Black Flag work, but 'Entertainment!' by Gang of Four and 'Los Angeles' by X don't work.

![image](https://github.com/GreenDiscord/vlc-rpc/assets/17746796/82aed382-96fa-4ef3-8e88-c2035155a66c)

**Comment by GreenDiscord** [comment]
You are finding errors I haven't seen yet, which is surprising. Is your music tagged? Does to have all metadata?

**Comment by sdasda7777** [comment]
It does have artist name and album name, not sure if anything else is necessary. They all work with Pigpog's release, but of course I had to manage the covers manually with that one.

![image](https://github.com/GreenDiscord/vlc-rpc/assets/17746796/045286d3-7b7d-401d-9eb4-1820ca099591)

![image](https://github.com/GreenDiscord/vlc-rpc/assets/17746796/5ed24204-f319-4029-873a-a5598310b7cc)

![image](https://github.com/GreenDiscord/vlc-rpc/assets/17746796/c470b403-b84b-4a51-a014-0eac6fd7dad7)

**Comment by GreenDiscord** [comment]
Can you by chance send me one of the files you are using? I'll use that to test it out.

**Comment by sdasda7777** [comment]
Here's the files, the song by Rancid is the only one that works for me. It's muted for copyright reasons, of course.

[songs1of2.zip](https://github.com/GreenDiscord/vlc-rpc/files/11611833/songs1of2.zip)
[songs2of2.zip](https://github.com/GreenDiscord/vlc-rpc/files/11611834/songs2of2.zip)

**Comment by GreenDiscord** [comment]
Should be fixed in https://github.com/GreenDiscord/vlc-rpc/releases/tag/V1.1.9
