### ISSUE TITLE
Clarify setup when `clone`ing repo in readme

### ISSUE THREAD

**Issue by sdasda7777** [GreenDiscord/vlc-rpc#50]
The setup guide currently doesn't mention cloning at all, I think someone tempted to clone the repo might forget to install the dependencies. I don't even remember how to do that anymore.

**Comment by GreenDiscord** [comment]
Should be fixed with [332919b](https://github.com/GreenDiscord/vlc-rpc/commit/332919b45b173db1eae72986fb5f7d42f9b06b0e)

**Comment by sdasda7777** [comment]
I've changed the structure a bit in #51
