### ISSUE TITLE
"state" length must be at least 2 characters long

### ISSUE THREAD

**Issue by sdasda7777** [GreenDiscord/vlc-rpc#6]
I'm geting this error when using 'apple' as source and playing a song by band called 'X'. I guess the issue is the band name is too short? 😜

![image](https://github.com/GreenDiscord/vlc-rpc/assets/17746796/064fb5d5-a7e8-44eb-8382-c5b7912418d2)

**Comment by GreenDiscord** [comment]
Yes your correct, I could and will updated it too add and extra like blank space to the state if the artist name is one letter or less.

**Comment by GreenDiscord** [comment]
Fixed. 
![image](https://github.com/GreenDiscord/vlc-rpc/assets/77177015/f7183d93-a79a-4105-8f59-1cc47872d97b)
