### ISSUE TITLE
Restore Pigpog's commits

### ISSUE THREAD

**Issue by sdasda7777** [GreenDiscord/vlc-rpc#7]
Hey, it appears that there are no commits from Pigpog or dylhack in this repo, which doesn't make sense, since it is a fork of a repo they contributed on. I believe that sort of steals the ownership of the code from them, and clearly is violation of the license they provided their code under.

Please try to restore the old commits. If there is ~100 commits by you here now and ~200 commits by them in the old repo, there should be ~300 commits in this repo.

**Comment by GreenDiscord** [comment]
Dylhack knows about this and pigpog does, neither have raised any issues. I have credited PigPog in the readme and now the description. I cannot though add their commits back.

**Comment by sdasda7777** [comment]
May be, but it is still wrong. You absolutely can add their commits, just clone the old repo and rebase this one onto it.

**Comment by GreenDiscord** [comment]
To add, i have added them to the license, which it should've been from the start, github just overwrited it.

**Comment by sdasda7777** [comment]
> You should be able to add their commits just fine, just clone the old repo and rebase this one onto it, then push it here.

Do note, though, that rewriting history is one of the more dangerous git operations, so if you were to do this, you should triple check everything went right before pushing here 😅

**Comment by GreenDiscord** [comment]
Yeah thats why I'm hestitant. I'll have a look, ty
