### ISSUE TITLE
Play/Pause icon is black on really dark gray

### ISSUE THREAD

**Issue by sdasda7777** [GreenDiscord/vlc-rpc#8]
I'm not sure why, but the play/pause icon seems to be black on really dark gray or something on this version, which is really hard to see:

![image](https://github.com/GreenDiscord/vlc-rpc/assets/17746796/66b10844-1298-461d-ac69-3f736be41256)

I believe on Pigpog's version the icons are black and white like this?

![image](https://github.com/GreenDiscord/vlc-rpc/assets/17746796/c79df306-bd24-4d03-beb8-8aaa007733ff)

**Comment by GreenDiscord** [comment]
Yeah, i thought i had that. I'll update now

**Comment by GreenDiscord** [comment]
![image](https://github.com/GreenDiscord/vlc-rpc/assets/77177015/19a614f3-3a50-4132-a0b5-0738b4e6ac03)

**Comment by sdasda7777** [comment]
Awesome, thanks! 😁
