### ISSUE TITLE
Crash if a video is opened

### ISSUE THREAD

**Issue by sdasda7777** [GreenDiscord/vlc-rpc#9]
Hey, I noticed the whole thing crashes if a video is opened. The correct behaviour is debatable (show nothing is playing? search using video specific metadata, in case it's a music video?), but I hope you can agree a crash shouldn't happen 😅

![image](https://github.com/GreenDiscord/vlc-rpc/assets/17746796/5a23a29b-8b9f-4967-915e-4e85241cf0e8)

**Comment by GreenDiscord** [comment]
https://github.com/GreenDiscord/vlc-rpc/commit/21decefae21ea3d0b4cffb9976beb6d860e45bf2 Should be fixed in most recent.
